@0xc4accc237846735d; # unique file id generated by 'capnp id'

struct Stop {
    name @0 : Text;
    lat  @1 : Float64;
    lng  @2 : Float64;
    code @3 : UInt32;
		servicePatternId @4 : UInt32;
		isStation @5 : Bool;
}

struct Stops {
    stops @0 : List(Stop);
}
